version: '3.4'

services:
  mongodb:
    image: mongo
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
  
  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.2
  
  rabbitmq:
    image: rabbitmq:3-management-alpine
  
  ocelot.apigateway:
    image: ${DOCKER_REGISTRY-}ocelotapigateway
    build:
      context: .
      dockerfile: Ocelot.ApiGateway/Dockerfile

  orderbook.application:
    image: ${DOCKER_REGISTRY-}orderbookapplication
    build:
      context: .
      dockerfile: OrderBook.Application/Dockerfile

  orderbook.api:
    image: ${DOCKER_REGISTRY-}orderbookapi
    build:
      context: .
      dockerfile: OrderBook.Api/Dockerfile

