apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: orderbook-worker
  name: orderbook-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: orderbook-worker
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/challengedigitas-default: "true"
        io.kompose.service: orderbook-worker
    spec:
      containers:
        - image: orderbookworker
          name: orderbook-worker
          resources: {}
      restartPolicy: Always
status: {}
